New Test File
loreum-org/loreum-token pull request #15
Opened 2023-07-11 14:07 UTC by jyotirmoydotdev

```bash
[⠒] Compiling...
[⠔] Compiling 4 files with 0.8.20
[⠑] Solc 0.8.20 finished in 2.38s
Compiler run successful with warnings:

Running 6 tests for test/foundry/LoreumToken.t.sol:Deployment
[PASS] test_LoreumToken_burn_restriction_account() (gas: 11538)
[PASS] test_LoreumToken_burn_restriction_amount(uint256) (runs: 256, μ: 23778, ~: 27269)
[PASS] test_LoreumToken_burn_state(uint256) (runs: 256, μ: 34579, ~: 34973)
[PASS] test_LoreumToken_init() (gas: 27697)
[PASS] test_LoreumToken_mint_restriction(uint256) (runs: 256, μ: 26298, ~: 26635)
[PASS] test_LoreumToken_mint_state(uint256) (runs: 256, μ: 35313, ~: 35620)
Test result: ok. 6 passed; 0 failed; 0 skipped; finished in 286.37ms

Running 11 tests for test/foundry/LoreTestCycle.t.sol:LoreumTokenTest
[PASS] testFail_MintFail(uint256) (runs: 256, μ: 21454, ~: 21484)
[PASS] test_AliceBurnToken(uint256) (runs: 256, μ: 73788, ~: 73788)
[PASS] test_AliceBurnTokenFail(uint256) (runs: 256, μ: 36321, ~: 36321)
[PASS] test_Basic() (gas: 40237)
[PASS] test_MintPass(uint256) (runs: 256, μ: 55413, ~: 55413)
[PASS] test_OwnerBurnToken(uint256) (runs: 256, μ: 48055, ~: 48055)
[PASS] test_TokenTransferFail(uint256) (runs: 256, μ: 39542, ~: 39542)
[PASS] test_TokenTransferSuccess(uint256) (runs: 256, μ: 67864, ~: 67864)
[PASS] test_TotalSupplyEqualToAllBalance(uint256) (runs: 256, μ: 70494, ~: 70494)
[PASS] test_transferFrom(uint256) (runs: 256, μ: 87041, ~: 87041)
[PASS] test_transferFromWithIncAllow(uint256) (runs: 256, μ: 124675, ~: 124676)
Test result: ok. 11 passed; 0 failed; 0 skipped; finished in 286.42ms
Ran 2 test suites: 17 tests passed, 0 failed, 0 skipped (17 total tests)
```

2023-07-11 15:35 UTC, xhad requested changes
Kindly add tests for changing the owner of the token.

2023-07-11 15:35 UTC, xhad commented on test/foundry/LoreTestCycle.t.sol
> +    function invarent() public {
Invariant is misspelled.

2023-07-11 15:35 UTC, xhad commented on test/foundry/LoreTestCycle.t.sol
> +        assertEq(lore.owner(), address(this));
This contract is ownable and the owner is expected to be changed.

2023-07-11 18:20 UTC, jyotirmoydotdev commented on test/foundry/LoreTestCycle.t.sol
> +    function invarent() public {
invarent -> invariant

2023-07-11 18:24 UTC, jyotirmoydotdev commented
```bash
[⠢] Compiling...
[⠒] Compiling 1 files with 0.8.20
[⠑] Solc 0.8.20 finished in 2.38s
Compiler run successful with warnings:

Running 6 tests for test/foundry/LoreumToken.t.sol:Deployment
[PASS] test_LoreumToken_burn_restriction_account() (gas: 11538)
[PASS] test_LoreumToken_burn_restriction_amount(uint256) (runs: 256, μ: 22995, ~: 27269)
[PASS] test_LoreumToken_burn_state(uint256) (runs: 256, μ: 34513, ~: 34973)
[PASS] test_LoreumToken_init() (gas: 27697)
[PASS] test_LoreumToken_mint_restriction(uint256) (runs: 256, μ: 26233, ~: 26635)
[PASS] test_LoreumToken_mint_state(uint256) (runs: 256, μ: 35226, ~: 35620)
Test result: ok. 6 passed; 0 failed; 0 skipped; finished in 222.07ms

Running 15 tests for test/foundry/LoreTestCycle.t.sol:LoreumTokenTest
[PASS] invariant() (runs: 256, calls: 3840, reverts: 3023)
[PASS] testFail_MintFail(uint256) (runs: 256, μ: 21432, ~: 21462)
[PASS] test_AliceBurnToken(uint256) (runs: 256, μ: 72112, ~: 72112)
[PASS] test_AliceBurnTokenFail(uint256) (runs: 256, μ: 32690, ~: 32690)
[PASS] test_Basic() (gas: 38604)
[PASS] test_MintPass(uint256) (runs: 256, μ: 53737, ~: 53737)
[PASS] test_OwnerBurnToken(uint256) (runs: 256, μ: 46423, ~: 46423)
[PASS] test_TokenTransferFail(uint256) (runs: 256, μ: 37844, ~: 37844)
[PASS] test_TokenTransferSuccess(uint256) (runs: 256, μ: 66231, ~: 66231)
[PASS] test_TotalSupplyEqualToAllBalance(uint256) (runs: 256, μ: 68841, ~: 68841)
[PASS] test_TransferOwnership() (gas: 37162)
[PASS] test_TransferOwnershipFail() (gas: 32125)
[PASS] test_TransferOwnershipToNULL() (gas: 31915)
[PASS] test_transferFrom(uint256) (runs: 256, μ: 85343, ~: 85343)
[PASS] test_transferFromWithIncAllow(uint256) (runs: 256, μ: 123333, ~: 123334)
Test result: ok. 15 passed; 0 failed; 0 skipped; finished in 572.06ms
Ran 2 test suites: 21 tests passed, 0 failed, 0 skipped (21 total tests)
```

2023-07-12 03:11 UTC, xhad approved these changes

2023-07-12 03:12 UTC, merged